[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "para_disk"
authors = [{name = "Flaherty", email = "kmf4@williams.edu"}]
dynamic = ["version", "description"]
